######################################################################
# Automatically generated by qmake (2.01a) Do 1. Mrz 07:52:25 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

QT += network

# Input
HEADERS += src/connection.h src/server.h
SOURCES += src/connection.cpp src/main.cpp src/server.cpp
